// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALut84eXyshPS0mhI3HwZ40pLqnOu3D8A',
    appId: '1:37877946600:web:4ea5ed2617e61d1533d15d',
    messagingSenderId: '37877946600',
    projectId: 'notes-app-pr',
    authDomain: 'notes-app-pr.firebaseapp.com',
    storageBucket: 'notes-app-pr.firebasestorage.app',
    measurementId: 'G-CNT88J29JR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqNhAn5brOpQH0odfhDWnQNya2jhSWNC4',
    appId: '1:37877946600:android:000a7c6bba46fdfd33d15d',
    messagingSenderId: '37877946600',
    projectId: 'notes-app-pr',
    storageBucket: 'notes-app-pr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD21-0cEnvneQuNE4e_aUK5EN3-KRjYEDg',
    appId: '1:37877946600:ios:776abcdfc1e07e7c33d15d',
    messagingSenderId: '37877946600',
    projectId: 'notes-app-pr',
    storageBucket: 'notes-app-pr.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD21-0cEnvneQuNE4e_aUK5EN3-KRjYEDg',
    appId: '1:37877946600:ios:776abcdfc1e07e7c33d15d',
    messagingSenderId: '37877946600',
    projectId: 'notes-app-pr',
    storageBucket: 'notes-app-pr.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALut84eXyshPS0mhI3HwZ40pLqnOu3D8A',
    appId: '1:37877946600:web:95b305918bdb636733d15d',
    messagingSenderId: '37877946600',
    projectId: 'notes-app-pr',
    authDomain: 'notes-app-pr.firebaseapp.com',
    storageBucket: 'notes-app-pr.firebasestorage.app',
    measurementId: 'G-RCLG16S0LW',
  );
}
